const BUILT_IN_LEXICON = {
  good: "maayo",
  morning: "aga",
  afternoon: "hapon",
  evening: "gab-i",
  hello: "kamusta",
  thank: "salamat",
  thanks: "salamat",
  you: "ikaw",
  please: "palihog",
  sorry: "pasaylo",
  yes: "huo",
  no: "indi",
  i: "ako",
  me: "ako",
  we: "kami",
  they: "sila",
  he: "siya",
  she: "siya",
  my: "akon",
  your: "imo",
  go: "kadto",
  went: "nagkadto",
  eat: "kaon",
  ate: "nagkaon",
  drink: "inom",
  sleep: "tulog",
  come: "kari",
  see: "kita",
  want: "gusto",
  love: "palangga",
  know: "kabalo",
  buy: "bakal",
  have: "may",
  are: "",
  is: "",
  am: "",
  was: "",
  do: "",
  market: "merkado",
  house: "balay",
  home: "balay",
  school: "eskwelahan",
  water: "tubig",
  food: "pagkaon",
  road: "dalan",
  street: "dalan",
  money: "kwarta",
  friend: "abyan",
  child: "bata",
  person: "tawo",
  day: "adlaw",
  night: "gab-i",
  today: "subong",
  tomorrow: "buas",
  yesterday: "kahapon",
  big: "daku",
  small: "gamay",
  many: "damo",
  beautiful: "matahum",
  happy: "malipayon",
  hungry: "gutom",
  tired: "kapoy",
  hot: "init",
  cold: "lamig",
  fast: "madasig",
  slow: "mahinay",
  how: "paano",
  what: "ano",
  where: "diin",
  who: "sin-o",
  when: "san-o",
  and: "kag",
  the: "",
  a: "",
  to: "sa",
  in: "sa",
  at: "sa",
  of: "sang",
  very: "tama",
  salamat: "salamat",
  kumusta: "kamusta",
  ako: "ako",
  gusto: "gusto",
  bahay: "balay",
  tubig: "tubig",
  pera: "kwarta",
  kanin: "kan-on",
  umaga: "aga",
  gabi: "gab-i",
  ngayon: "subong",
  bukas: "buas",
  kahapon: "kahapon",
  saan: "diin",
  ano: "ano",
  one: "isa",
  two: "duha",
  three: "tatlo",
  four: "apat",
  five: "lima",
  six: "anom",
  seven: "pito",
  eight: "walo",
  nine: "siyam",
  ten: "napulo",
  week: "semana",
  month: "bulan",
  year: "tuig",
  hour: "oras",
  now: "subong",
  later: "karon",
  always: "pirme",
  never: "wala gid",
  mother: "nanay",
  father: "tatay",
  brother: "utod",
  sister: "utod",
  woman: "babae",
  man: "lalaki",
  teacher: "maestra",
  student: "estudyante",
  work: "trabaho",
  walk: "lakat",
  run: "dalagan",
  read: "basa",
  write: "sulat",
  speak: "hambal",
  listen: "pamati",
  help: "bulig",
  give: "hatag",
  take: "kuha",
  wait: "hulat",
  cook: "luto",
  wash: "hugas",
  open: "abri",
  close: "sira",
  bad: "malain",
  new: "bag-o",
  old: "tigulang",
  near: "malapit",
  far: "malayo",
  easy: "mahapos",
  hard: "mabudlay",
  clean: "matinlo",
  dirty: "mahigko",
  angry: "akig",
  afraid: "hadlok",
  city: "syudad",
  town: "banwa",
  church: "simbahan",
  store: "tindahan",
  hospital: "hospital",
  car: "salakyan",
  book: "libro",
  work_place: "opisina",
  rice: "kan-on",
  fish: "isda",
  meat: "karne",
  fruit: "prutas",
  because: "kay",
  but: "pero",
  also: "man",
  here: "diri",
  there: "didto",
  this: "ini",
  that: "ina",
  all: "tanan",
  maganda: "matahum",
  mabilis: "madasig",
  trabaho: "trabaho",
  araw: "adlaw",
  pamilya: "pamilya",
  kaibigan: "abyan",
  pagkain: "pagkaon",
  mahal: "palangga",
  magandang: "maayo nga",
  marami: "damo",
  maraming: "madamo",
  po: "",
  opo: "huo",
  hindi: "indi",
  wala: "wala",
  mayroon: "may",
  meron: "may",
  may: "may",
  kailangan: "kinahanglan",
  kailanganin: "kinahanglan",
  tulong: "bulig",
  tulungan: "buligan",
  pangalan: "ngalan",
  pangalanan: "ngalanan",
  pupunta: "makadto",
  pumunta: "magkadto",
  punta: "kadto",
  galing: "naghalin",
  nakatira: "naga-istar",
  oras: "oras",
  magkano: "tagpila",
  ito: "ini",
  iyan: "ina",
  iyon: "ato",
  dito: "diri",
  diyan: "dira",
  doon: "didto",
  bakit: "nga-a",
  sino: "sin-o",
  kailan: "san-o",
  paano: "paano",
  ilan: "pila",
  anong: "ano",
  ang: "ang",
  ng: "sang",
  mga: "mga",
  sa: "sa",
  para: "para",
  ko: "ko",
  mo: "mo",
  niya: "niya",
  namin: "namon",
  natin: "naton",
  ninyo: "ninyo",
  nila: "nila",
  kayo: "kamo",
  tayo: "kita",
  kami: "kami",
  sila: "sila",
  siya: "siya",
  ako: "ako",
  ikaw: "ikaw",
  ka: "ka",
  ligtas: "luwas",
  delikado: "delikado",
  ospital: "hospital",
  doktor: "doktor",
  gamot: "bulong",
  lagnat: "hilanat",
  sakit: "kasakit",
  sugat: "pilas",
  ubo: "ubo",
  hilo: "lipong",
  nahihilo: "nagalipong",
  kamay: "kamot",
  hugasan: "hugasan",
  bago: "antes",
  pagkatapos: "pagkatapos",
  kumain: "magkaon",
  pagkain: "pagkaon",
  tubig: "tubig",
  baha: "baha",
  ulan: "ulan",
  malakas: "mabaskog",
  mabilis: "madasig",
  daan: "dalan",
  kalsada: "dalan",
  tulay: "taytay",
  tawid: "tabok",
  tumawid: "magtabok",
  tumawag: "tawag",
  tawagan: "tawgan",
  sabihin: "hambalon",
  sabi: "siling",
  guro: "maestra",
  estudyante: "estudyante",
  klase: "klase",
  libro: "libro",
  kwento: "sugilanon",
  tanong: "pamangkot",
  sagot: "sabat",
  sagutin: "sabton",
  basahin: "basahon",
  sulat: "sulat",
  isulat: "isulat",
  porma: "porma",
  opisina: "opisina",
  serbisyo: "serbisyo",
  libre: "libre",
  bayad: "bayad",
  pera: "kwarta",
  trabaho: "trabaho",
  ulat: "report",
  report: "report",
  iskedyul: "iskedyul",
  pulong: "miting",
  meeting: "miting",
  pamilya: "pamilya",
  nanay: "nanay",
  tatay: "tatay",
  kapatid: "utod",
  kaibigan: "abyan",
  bahay: "balay",
  paaralan: "eskwelahan",
  simbahan: "simbahan",
  tindahan: "tindahan",
  palengke: "merkado",
  merkado: "merkado",
  bukas: "buas",
  ngayon: "subong",
  kahapon: "kahapon",
  mamaya: "karon pa",
  lagi: "pirme",
  muna: "anay",
  pa: "pa",
  na: "na",
  din: "man",
  rin: "man",
  pero: "pero",
  dahil: "kay",
  kung: "kon",
  kapag: "kon",
  bago: "antes",
  hanggang: "tubtob",
  mula: "halin",
  dalhin: "dalhon",
  dala: "dala",
  buksan: "abrihan",
  isara: "sirhan",
  pinto: "puwertahan",
  susi: "yabi",
  mesa: "lamesa",
  upuan: "pulungkuan",
  bag: "bag",
  pangalan: "ngalan",
  lugar: "lugar",
  mataas: "mataas",
  mababa: "manubo",
  luma: "daan",
  bago: "bag-o",
  mainit: "init",
  malamig: "lamig",
  mahal: "mahal",
  mura: "barato",
  mabuti: "maayo",
  masama: "malain",
  will: "maga",
  need: "kinahanglan",
  call: "tawga",
  doctor: "doktor",
  if: "kon",
  fever: "hilanat",
  tonight: "karon nga gab-i",
  class: "klase",
  cancelled: "ginkanselar",
  canceled: "ginkanselar",
  rain: "ulan",
  strong: "mabaskog",
  students: "mga estudyante",
  should: "dapat",
  module: "modyul",
  left: "ginbilin",
  key: "yabi",
  table: "lamesa",
  not: "indi",
  inside: "sa sulod",
  bag: "bag",
  can: "mahimo",
  explain: "ipathag",
  hiligaynon: "Hiligaynon",
  elders: "mga tigulang",
  understand: "maintindihan",
  cross: "magtabok",
  bridge: "taytay",
  rising: "nagataas",
  quickly: "madasig",
  take: "imna",
  medicine: "bulong",
  after: "pagkatapos",
  eating: "magkaon",
  before: "antes",
  breakfast: "pamahaw",
  pakisabi: "palihog hambala",
  guro: "maestra",
  mahuhuli: "maulihi",
  dahil: "kay",
  walang: "wala sing",
  masasakyan: "masakyan",
  online: "online",
  "online-class": "online class",
  weak: "maluya",
  internet: "internet",
  bring: "magdala",
  valid: "balido",
  id: "ID",
  full: "bug-os",
  name: "ngalan",
  form: "porma",
  said: "nagsiling",
  would: "maga",
  early: "temprano",
  field: "talamnan",
  needs: "kinahanglan",
  gate: "puwertahan",
  yet: "anay",
  pain: "kasakit",
  gets: "maga",
  worse: "maglala",
  immediately: "dayon",
  huwag: "indi",
  mong: "mo",
  kalimutang: "pagkalimti",
  isara: "sirhan",
  pinto: "puwertahan",
  bago: "antes",
  umalis: "maghalin",
  send: "ipadala",
  report: "report",
  lunch: "panyaga",
  para: "agod",
  "ma-review": "marepaso",
  stay: "magpabilin",
  outside: "sa guwa",
  until: "tubtob",
  building: "bilding",
  checked: "masusi",
  rescue: "rescue",
  team: "team",
  office: "opisina",
  from: "halin",
  eight: "walo",
  five: "lima",
  read: "basaha",
  story: "sugilanon",
  first: "anay",
  then: "dayon",
  answer: "sabton",
  questions: "mga pamangkot",
  end: "katapusan",
  visitors: "mga bisita",
  so: "gani",
  "i-check": "tan-awa",
  schedule: "iskedyul",
  meeting: "miting",
  kita: "kita",
  hands: "mga kamot",
  touching: "hikapon",
  wound: "pilas",
  family: "pamilya",
  tell: "hambala",
  them: "sila",
  safe: "luwas",
  libre: "libre",
  serbisyong: "serbisyo",
  ito: "ini",
  senior: "senior",
  citizen: "citizen",
  handle: "halongi",
  carefully: "sing maayo",
  kung: "kon",
  nahihilo: "nagalipong",
  ka: "ka",
  sit: "magpungko",
  down: "",
  anay: "anay",
  manager: "manedyer",
  approved: "gin-aprubahan",
  request: "pangabay",
  payment: "bayad",
  ready: "handa",
  harvest: "pag-aniha",
  still: "pa",
  ripe: "mahinog",
  lumipat: "magsaylo",
  kayo: "kamo",
  mas: "mas",
  mataas: "mataas",
  lugar: "lugar",
  patuloy: "nagapadayon",
  baha: "baha",
  cannot: "indi mahimo",
  ask: "mangayo",
  staff: "staff",
};

const SEED_TRANSLATIONS = new Map([
  [
    "good morning i will go to the market because we need food",
    "Maayong aga, makadto ako sa merkado kay kinahanglan namon sang pagkaon.",
  ],
  [
    "please call the doctor if the child has a fever tonight",
    "Palihog tawga ang doktor kon may hilanat ang bata karon nga gab-i.",
  ],
  [
    "the class was cancelled because the rain was strong but students should read the module at home",
    "Ginkanselar ang klase kay mabaskog ang ulan, pero dapat basahon sang mga estudyante ang modyul sa balay.",
  ],
  [
    "i left the key on the table not inside the bag",
    "Ginbilin ko ang yabi sa lamesa, indi sa sulod sang bag.",
  ],
  [
    "can you explain this in hiligaynon so the elders can understand",
    "Mahimo mo bala ini ipathag sa Hiligaynon agod maintindihan sang mga tigulang?",
  ],
  [
    "do not cross the bridge because the water is rising quickly",
    "Indi magtabok sa taytay kay madasig nga nagataas ang tubig.",
  ],
  [
    "take this medicine after eating not before breakfast",
    "Imna ini nga bulong pagkatapos magkaon, indi antes sang pamahaw.",
  ],
  [
    "pakisabi sa guro na mahuhuli ako dahil walang masasakyan",
    "Palihog hambala ang maestra nga maulihi ako kay wala sing masakyan.",
  ],
  [
    "nag-online class ako today pero weak ang internet sa balay",
    "Nag-online class ako subong nga adlaw pero maluya ang internet sa balay.",
  ],
  [
    "bring one valid id and write your full name on the form",
    "Magdala sang isa ka balido nga ID kag isulat ang bug-os mo nga ngalan sa porma.",
  ],
  [
    "she said she would wait here but she went home early",
    "Nagsiling siya nga magahulat siya diri, pero nagpuli siya sing temprano.",
  ],
  [
    "the rice field needs water but do not open the gate yet",
    "Kinahanglan sang tubig ang talamnan sang humay, pero indi anay pag-abrihan ang puwertahan.",
  ],
  [
    "if the pain gets worse go to the hospital immediately",
    "Kon maglala ang kasakit, magkadto dayon sa hospital.",
  ],
  [
    "huwag mong kalimutang isara ang pinto bago ka umalis",
    "Indi pagkalimti nga sirhan ang puwertahan antes ka maghalin.",
  ],
  [
    "please send the report before lunch para ma-review ko",
    "Palihog ipadala ang report antes sang panyaga agod marepaso ko.",
  ],
  [
    "stay outside until the building is checked by the rescue team",
    "Magpabilin sa guwa tubtob masusi sang rescue team ang bilding.",
  ],
  [
    "the office is open from eight in the morning until five in the afternoon",
    "Abri ang opisina halin alas otso sang aga tubtob alas singko sang hapon.",
  ],
  [
    "read the story first then answer the questions at the end",
    "Basaha anay ang sugilanon, dayon sabta ang mga pamangkot sa katapusan.",
  ],
  [
    "the food is for the visitors so please do not eat it yet",
    "Para sa mga bisita ang pagkaon, gani palihog indi anay ini pagkauna.",
  ],
  [
    "i-check mo ang schedule kay may meeting kita later",
    "Tan-awa ang iskedyul kay may miting kita karon pa.",
  ],
  [
    "wash your hands before touching the wound",
    "Hugasi ang imo mga kamot antes hikapon ang pilas.",
  ],
  [
    "call your family and tell them you are safe",
    "Tawgi ang imo pamilya kag hambala sila nga luwas ka.",
  ],
  [
    "libre ang serbisyong ito para sa mga senior citizen",
    "Libre ini nga serbisyo para sa mga senior citizen.",
  ],
  [
    "the road is near the church not near the school",
    "Ang dalan malapit sa simbahan, indi malapit sa eskwelahan.",
  ],
  [
    "because the book is old handle it carefully when you read it",
    "Kay tigulang na ang libro, halongi ini kon basahon mo.",
  ],
  [
    "kung nahihilo ka sit down anay and drink water",
    "Kon nagalipong ka, magpungko anay kag mag-inom sang tubig.",
  ],
  [
    "the manager approved the request but the payment is not ready yet",
    "Gin-aprubahan sang manedyer ang pangabay, pero indi pa handa ang bayad.",
  ],
  [
    "do not harvest the fruit today because it is still not ripe",
    "Indi pag-aniha ang prutas subong kay wala pa ini mahinog.",
  ],
  [
    "lumipat kayo sa mas mataas na lugar kung patuloy ang baha",
    "Magsaylo kamo sa mas mataas nga lugar kon nagapadayon ang baha.",
  ],
  [
    "if you cannot read the form ask the staff for help",
    "Kon indi mo mabasa ang porma, mangayo sang bulig sa staff.",
  ],
]);

const TAGALOG_PHRASE_TRANSLATIONS = new Map([
  ["magandang umaga", "Maayong aga."],
  ["magandang hapon", "Maayong hapon."],
  ["magandang gabi", "Maayong gab-i."],
  ["kumusta ka", "Kamusta ka?"],
  ["kamusta ka", "Kamusta ka?"],
  ["maraming salamat", "Madamo gid nga salamat."],
  ["salamat po", "Salamat gid."],
  ["pasensya na", "Pasensya na."],
  ["tulungan mo ako", "Buligi ako."],
  ["hindi ko alam", "Wala ko kabalo."],
  ["mahal kita", "Palangga ta ka."],
  ["ano ang pangalan mo", "Ano imo ngalan?"],
  ["saan ka pupunta", "Diin ka makadto?"],
  ["saan ka galing", "Diin ka naghalin?"],
  ["saan ka nakatira", "Diin ka naga-istar?"],
  ["anong oras na", "Ano ang oras subong?"],
  ["magkano ito", "Tagpila ini?"],
  ["gusto ko ito", "Nanamian ko sini."],
  ["gusto ko tubig", "Gusto ko sang tubig."],
  ["kailangan ko ng tulong", "Kinahanglan ko sang bulig."],
  ["nasaan ang ospital", "Diin ang hospital?"],
  ["pumunta ka sa ospital", "Magkadto ka sa hospital."],
  ["huwag kang tumawid", "Indi ka magtabok."],
  ["bawal tumawid", "Indi pwede magtabok."],
  ["may baha sa daan", "May baha sa dalan."],
  ["malakas ang ulan", "Mabaskog ang ulan."],
  ["walang pasok ngayon", "Wala sing klase subong."],
  ["kanselado ang klase", "Ginkanselar ang klase."],
  ["pakisabi sa guro", "Palihog hambala ang maestra."],
  ["basa ang libro", "Basaha ang libro."],
  ["isulat ang pangalan mo", "Isulat ang imo ngalan."],
  ["dalhin ang valid id", "Magdala sang balido nga ID."],
  ["libre ang serbisyo", "Libre ang serbisyo."],
  ["para sa senior citizen", "Para sa senior citizen."],
  ["tumawag sa pamilya mo", "Tawgi ang imo pamilya."],
  ["ligtas ako", "Luwas ako."],
]);

function normalizeText(text) {
  return text
    .toLowerCase()
    .replace(/[^\p{L}\p{N}\s'-]/gu, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function translatePhrase(text) {
  return TAGALOG_PHRASE_TRANSLATIONS.get(normalizeText(text));
}

function translateDict(text) {
  const output = [];

  for (const raw of text.split(/\s+/)) {
    const match = raw.match(/^(\W*)(.*?)(\W*)$/u);
    if (!match) continue;
    const [, lead, core, trail] = match;
    const key = core.toLowerCase();

    if (Object.prototype.hasOwnProperty.call(BUILT_IN_LEXICON, key)) {
      let translated = BUILT_IN_LEXICON[key];
      if (!translated) continue;
      if (/^[A-Z]/.test(core)) {
        translated = translated.slice(0, 1).toUpperCase() + translated.slice(1);
      }
      output.push(`${lead}${translated}${trail}`);
    } else {
      output.push(`${lead}*${core}*${trail}`);
    }
  }

  return output.join(" ");
}

export default function handler(req, res) {
  if (req.method !== "POST") {
    res.setHeader("Allow", "POST");
    return res.status(405).json({ error: "Method not allowed" });
  }

  const text = typeof req.body?.text === "string" ? req.body.text.trim() : "";
  if (!text) return res.status(200).json({ translation: "" });

  const seedTranslation = SEED_TRANSLATIONS.get(normalizeText(text));
  if (seedTranslation) {
    return res.status(200).json({
      translation: seedTranslation,
      backend: "seed-reference-unverified",
      note: "Matched a seed benchmark prompt. This reference still needs native-speaker review.",
    });
  }

  const phraseTranslation = translatePhrase(text);
  if (phraseTranslation) {
    return res.status(200).json({
      translation: phraseTranslation,
      backend: "tagalog-phrase-baseline",
      note: "Matched a curated demo phrase. This still needs native-speaker review.",
    });
  }

  return res.status(200).json({
    translation: translateDict(text),
    backend: "expanded-dict-baseline",
  });
}
